---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: result

# delete instances with "QA" in name
- name: Delete instances
  os_server:
    cloud: openstack
    name: "{{ item['name'] }}"
    state: 'absent'
  when: item.metadata['deployment_name'] == 'QA'
  loop: "{{ result['openstack_servers'] }}"
