- hosts: frontends
  gather_facts: false
  tasks:
  - name: Curl website
    uri:
      url: "http://localhost"
      return_content: yes
      status_code: 200
    register: webpage
        
  - debug: var=webpage.content

  - name: Fail if 'Ansible' is not in the page content
    fail:
    when: "'Ansible' not in webpage.content"
