---
# Additions to this file are commented inline
osp_servers:
  - name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: frontend
# nic for internal network
    nics:
      - net-name: int_network
    meta: "group=frontends,deployment_name=QA"
#
# Add "userdata" to inject osp keys
#
    userdata: |
      #!/bin/bash 
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  - name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
# nic for internal network
    nics:
      - net-name: int_network
    meta: "group=apps,deployment_name=QA"
#
# Add "userdata" to inject osp keys
#
    userdata: |
      #!/bin/bash 
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  - name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
# nic for internal network
    nics:
      - net-name: int_network
    meta: "group=apps,deployment_name=QA"
#
# Add "userdata" to inject osp keys
#
    userdata: |
      #!/bin/bash 
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  - name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: db
    nics:
      - net-name: int_network
# nic for internal network
    meta: "group=appdbs,deployment_name=QA"
#
# Add "userdata" to inject osp keys
#
    userdata: |
      #!/bin/bash 
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
