---
instance_list:
 - name: app1
   #image: rhel-guest
   group: apps
   meta_deployment: QA
   meta_group: app_servers
   security_group_name: apps

 - name: app2
   group: apps
   #image: rhel-guest
   meta_deployment: QA
   meta_group: app_servers
   security_group_name: apps

 - name: db
   group: appdbs
   #image: rhel-guest
   meta_deployment: QA
   meta_group: database_servers 
   security_group_name: db

 - name: frontend
   group: frontends
   #image: rhel-guest
   meta_deployment: QA
   meta_group: load_balancers 
   security_group_name: frontend
