---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

# Create repo dir 
#- name: Create yum.repo.d dir
#  file:
#    path: /etc/yum.repos.d
#    state: directory

# Now copy over repos from template to host
- name: Enable repos from template
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/internal.repo
    owner: root
    group: root
    mode: '0644'

# Install a couple user apps
- name: install 
  yum:
    name: ['vim', 'tree', 'python-pip']
    state: latest
